[project]
name = "btc-rocks"
costs_version = 1

[[project.requirements]]
contract_id = "SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ.boom-nfts"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.boom-nfts]
path = "contracts/external/boom-nfts.clar"
depends_on = []


[contracts.commission-nop]
path = "contracts/external/commission-nop.clar"
depends_on = []

[contracts.commission-trait]
path = "contracts/external/commission-trait.clar"
depends_on = []

[contracts.btc-rocks]
path = "contracts/btc-rocks.clar"
depends_on = ["commission-trait"]


[contracts.btc-rocks-mint]
path = "contracts/btc-rocks-mint.clar"
depends_on = ["btc-rocks"]
