
[project]
name = "backend-rescue"
authors = []
telemetry = false
analysis = ["check_checker"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.btc-rocks"

[contracts.btc-rocks-rescue]
path = "contracts/btc-rocks-rescue.clar"
depends_on = []
