
[project]
name = "backend-rescue"
authors = []
telemetry = false

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.btc-rocks"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true

[contracts.support-btc-rocks-transfer]
path = "contracts/support-btc-rocks-transfer.clar"
depends_on = []
