name: CI
on: [push]
jobs:
  tests:
    name: "Test contracts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: test --coverage --manifest-path=./backend-public/Clarinet.toml
      - name: "Export code coverage"
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.lcov
