name: CI
on: [push]
jobs:
  tests:
    name: "Test contracts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Execute test suite"
        uses: docker://ludovic/clarinet:latest
        with: 
          args: test --coverage
      - name: "Export code coverage"
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.lcov
